openapi: 3.0.1
info:
  title: A
  version: 1.0.0

paths: {}
 
components:
  schemas:
    CommonCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-xxx: 'CommonCategory'
          example: 'CommonCategory'
        commonCategory:
          type: string
    